name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install check packages
        run: sudo apt-get install check-dev
      - name: cmake cversion
        run: cmake --version
      - name: create configs
        run: cmake .
      - name: make
        run: make
      - name: unit tests
        run: ctest -V