name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install automake autoconf libtool libsubunit-dev valgrind
      - name: compile & install check
        run: scripts/install-check.sh
      - name: cmake cversion
        run: cmake --version
      - name: create configs
        run: cmake .
      - name: make
        run: make
      - name: unit tests
        run: |
          make checks
          CK_FORK=no ctest -T memcheck